<?php include('header.php'); ?>

<style >
    .box{
        background-color: rgba(100, 120, 140, 0.9);
        border-radius: 10px;
        color: #fff;
    }

    @media screen and (min-width: 992px) {
        .box {
            background-color: rgba(100, 120, 140, 0.8) ;
        }
    }
h1,
h2,
h3,
h4,
h5,
h6 {
  margin: 0 0 20px 0;
  text-transform: none;
  color: rgba(254, 82, 76, 1);
  font-family: "Raleway", "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-weight: 600;
  letter-spacing: 1px;
  line-height: 1.5;
}

/*Active Menu*/
.dropdown #subsysM{
  background-color: #3B5998;
  color: #fff;}

</style>
  
<section  style="background-image: url(images/subsysBG/mechBG.png);background-size: cover; ">
    
    <div class="pricing-area" style="margin-top: -30px;" >
        <div class="container">
            <div class="row">

              <div class="col-md-5">
                <div class="box">
                  <h3 style="font-size: 48px;padding-left: 10px; margin-bottom: 5px;">MECHANICAL</h3>
                  <div style="font-size :16px;text-align: left;padding: 0px 15px 15px 15px;">
                        <p align="justify">The mechanical subsystem consists of three sections: <b>Structures</b>, <b>Thermals</b> and <b>Integration</b>. The broad function of this subsystem is to design the body of the satellite and mount all
                    components on it, shielding them well from shock, excessive temperatures, radiation and stray
                    magnetic fields, control the internal thermal environment at all times and design mechanisms
                    crucial to the working of components.</p>

                        <p align="justify">This subsystem is responsible for choosing the optimal shape, material and framework for the
                    satellite body by simulating loading conditions during launch and in orbit, communicate weight
                    and dimension constraints to other subsystems, provide means of mounting, fastening and
                    cushioning all components securely, dissipate excess heat generated by the components,
                    maintain steady temperature conditions within the satellite and protect the components from
                    the harsh space environment, provide routing for the various power and data cables used,
                    interface the satellite to the launch vehicle and fabricate the final flight model of the satellite
                    and test it for resistance to shocks and thermal vacuum conditions.</p>
      
                </div>
              </div>

              <div class=" col-md-7">
                </div>
                       
              
            </div>
        </div>
    </div>

</section>

<?php include('footer.php'); ?>

    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/jquery.isotope.min.js"></script>
    <script src="js/main.js"></script>
    <script src="js/wow.min.js"></script>
  <script src="js/fittext.js"></script>
    <script src="js/lettering.js"></script>
    <script src="js/textillate.js"></script>
    <script>
    $(function () {
        $('.tlt').textillate({
            loop: true,
            minDisplayTime: 4000,
            in: {
                effect: 'fadeInLeftBig',
                delayScale: 1.5,
                delay: 50,
                sync: true,
                shuffle: false,
                reverse: false,
                },

            out: {
                effect: 'fadeOutRightBig',
                delayScale: 1.5,
                delay: 50,
                sync: true,
                shuffle: false,
                reverse: true,
                },
        });
    })
    </script>
</body>
</html>
