<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Abhishek V. Potnis">
    <title> Structures Sub-System | Pratham - IIT Bombay Student Satellite Initiative</title>
	
	<!-- core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="css/colorbox.css" />
	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
    <section class="pricing-area" >
        <div class="container">
           <div class="center wow fadeInDown">
             
<h2 style="text-align:left;"> Structures Sub-System</h2>

<p align="justify">The Structures, Thermals and Mechanisms group has under its aegis the physical units comprising the body of the satellite.</p>

<p align="justify">The broad function of this group is to design the body of the satellite and mount all components on it, shielding them well from shock, excessive temperatures, radiation and stray magnetic fields, control the
internal thermal environment at all times and design mechanisms crucial to the working of components.</p>

<br>
<p align="justify">The following are the responsibilities of the group -</p>
<p align="justify">1. To choose the optimal shape, material and kind of framework for the satellite body by simulating loading conditions during launch and in orbit.</p>
<p align="justify">2. To allocate resources of weight and dimension to all other teams.</p>
<p align="justify">3. To provide means of mounting onboard, fastening and cushioning all components securely.</p>
<p align="justify">4. To dissipate excess heat generated by the components within, protect internal components from the harsh space environment and maintain safe and steady thermal conditions within the satellite.</p>
<p align="justify">5. To design a stable structure with moments conforming to the requirements dictated by the Attitude Control group.</p>
<p align="justify">6. To design mechanisms for the smooth deployment of booms and antennae and facilitate communication by rotating the antennae to point towards the ground station.</p>
<p align="justify">7. To provide routing for the various power and data cables used, interface all components to each other and interface the satellite to the launch vehicle.</p>
<p align="justify">8. To fabricate the prototype and final flight models of the satellite.</p>
<p align="justify">9. To test the satellite model for resistance to shocks and thermal vacuum conditions.</p>
</html>