<?php	include('header.php');?>
<h3>The Structures Subsystem</h3>


  <p align="justify"><img src="images/structures.jpg" alt="" width="336" height="262" class="float_right" />The Structures, Thermals and Mechanisms group has under its aegis the
    physical units comprising the body of the satellite.</p>
  <p align="justify">The broad
    function of this group is to design the body of the satellite and mount all components on it, shielding them well from shock, excessive
    temperatures, radiation and stray magnetic fields, control the<br />
    internal thermal environment at all times and design mechanisms
    crucial to the working of components.</p>
  <p align="justify"><br />
    The following are the responsibilities of the group -<br />
    1. To choose the optimal shape, material and kind of framework for the
    satellite body by simulating loading conditions during launch and in
    orbit.<br />
    2. To allocate resources of weight and dimension to all other teams.<br />
    3. To provide means of mounting onboard, fastening and cushioning all 
    components securely.<br />
    4. To dissipate excess heat generated by the components within, 
    protect internal components from the harsh space environment and
    maintain safe and steady thermal conditions within the satellite.<br />
    5. To design a stable structure with moments conforming to the
    requirements dictated by the <a href="controls.html">Attitude Control</a> group.<br />
    6. To design mechanisms for the smooth deployment of booms and
    antennae and facilitate communication by rotating the antennae to 
    point towards the ground station.<br />
    7. To provide routing for the various power and data cables used,
    interface all components to each other and interface the satellite to
    the launch vehicle.<br />
    8. To fabricate the prototype and final flight models of the
    satellite.<br />
    9. To test the satellite model for resistance to shocks and thermal
    vacuum conditions.</p>
  <p align="justify">These students work in the Structures Sub-system:</p>
   <table width="531" height="76" border="0">
    <tr>
      <td height="33">Name</td>
      <td>Department</td>
      </tr>
	<tr>
      <td height="31"><span class="style1"> Shantanu Shahane</span></td>
      <td>Mechanical Engineering </td>
    </tr>
     <tr>
      <td height="38"><span class="style1">Yashu Vishnalia</span></td>
      <td><span class="style1">Mechanical Engineering </span></td>
    </tr>
     <tr>
      <td height="31"><span class="style1">Khushboo Shrivastava </span></td>
      <td>Mechanical Engineering </td>
    </tr>
    <tr>
      <td height="38"><span class="style1">Ishan Rakshit</span></td>
      <td><span class="style1">Aerospace Engineering </span></td>
    </tr>
    <tr>
      <td height="38"><span class="style1">Mayur Varade</span></td>
      <td><span class="style1">Energy Sciences</span></td>
    </tr>
    <tr>
      <td height="38"><span class="style1">Ratnesh Mishra</span></td>
      <td><span class="style1">Aerospace Engineering </span></td>
    </tr>
    </table>
  <p>Given below are the graduated students who worked in the Structures Sub-system:<br />
  </p>
  <table width="531" height="76" border="0">
    <tr>
      <td height="33">Name</td>
      <td>Department</td>
      <td>Role and Tenure </td>
      </tr>
	<tr>
      <td height="31"><span class="style1"> Niranjan Parab(head)</span></td>
      <td>Aerospace Engineering </td>
      <td> Head (July 2008 - June 2010) </td>
    </tr>
     <tr>
      <td height="31"><span class="style1">Ramanath Pai </span></td>
      <td>Mechanical Engineering </td>
      <td>Member (July 2008 - March 2010) </td>
    </tr>
    <tr>
      <td height="38"><span class="style1">Ankit Chiplunkar</span></td>
      <td><span class="style1">Aerospace Engineering </span></td>
      <td>Member (July 2009 - March 2011)<br /> Head (July 2010 -March 2011)
    </tr>
    
  </table>
<?php	include('footer.php');?>
