<?php	include('header.php');?>
<h3 class="style2">Timeline</h3>

<p align="justify"><b>Background</b><br /><br />
The challenge to build a Student Satellite was taken up by two Aerospace Department students namely <i>Saptarshi Bandyopadhyay</i> and <i>Shashank Tamaskar</i>, around July 2007. The feasibility of the concept was proved to the Aerospace Department, which agreed to support the team in this initiative. During September &ndash; October 2007, a team was chosen from amongst the students spanning various departments and batches. During December 2008, the team worked together and understood some of the essentials that were required for a project of this magnitude. Work on the Satellite began in full earnest from January 2008. In February, the project-managers and team leaders of all Sub-Systems went to ISAC (ISRO Satellite Center) Bangalore, where they interacted with Raghava Murthy (Project Director, Small Satellite Project) and his team of engineers who reviewed our progress. Finally after months of debating and reviewing, the Payload for our first Satellite was chosen to be Total Electron Count of the Ionosphere, around May 2008. <br /><br />
    During the Summer Vacations (May-July, 2008), the team worked on the Conceptual Design of the Satellite which culminated in the Conceptual Design Review (CDR) held within IIT Bombay on 31st July 2008, which was attended by a number of faculty members. Then the entire team of 33 students went to ISAC in August for the project CDR. It was attended by Dr Raghava Murthy and other Project Directors and Engineers. The team was lauded for the work done so far and suggestions were  givn for improvement. The next milestone for the Satellite project is the Preliminary Design Review.
<p align="justify">  The project is under the aegis of the Aerospace Department,  but is truly an institute level project as the work  involves many other departments like Electrical, Mechanical, etc. About 20  faculty members belonging to Aerospace, Electrical,  Mechanical and Computer Science Departments are involved with the project. Although 'Pratham' is a student  initiative, the team leader for Pratham is Prof. Sudhakar from Aerospace Engineering Department. &nbsp;&nbsp;
<p align="justify">  All through the project, a lot of emphasis  has been given to documentation of the work. Detailed descriptions of the  methodology and the results of the work done by the team have been included in  the documentation. The Requirements Capture Report was written during the  months of March &ndash; May 2008. The Conceptual Design Report was written after the  Conceptual Design was finalised in July 2008. These reports are archived in our  website and will serve as stepping stones for the future projects.
<p align="left">The project has been divided into 4 phases:</p>
  <p align="left" class="style4" style="font-weight: bold">Phase I: Conceptual Designing (Dec 07-Aug 08)</p>
  <p align="justify">The phase began with a 1 month project on functional decomposition, defining interfaces, building components and sythesising the system in December 2007. This was a training ground where we learnt that satellite making is a tricky business and importance of working as a team.<br />
    In Feburary the team went on a trip to ISAC Banglore where we interacted with Dr. Raghavmurthy and his team of system engineers who reviewed our progress. This trip made us realise the importance of system integration and documentation for our project.<br />
    Over the next two months we spent many hours debating over the feasibility of our payload At the same time the team continued to learn the intricacies of the individual subsystems.<br />
    In the month of April and May we had extensive reviews of our work and we finally converged onto a payload.</p>
  <p align="left" class="style4"><span style="font-weight: bold">Phase II: Preliminary Design (Sep 08-Dec 09)</span><br />
  </p>
  <p align="justify">This is the next step in any design process after the payload has been identified and its requirements from various subsystems known.</p>
  <p align="justify">    This is where we fix what components go into making individual subsystems.</p>
  <p class="style4" style="font-weight: bold">Phase III: Detailed Design (Dec 09-June 10)</p>
  <p align="justify">    Once we procure various components and have a hands on experience with them we will enter into the detailed design phase. In this phase we will be dealing with various nitty-gritty details on each of the components and how to join them together to make a prototype model. </p>
  <p class="style4" style="font-weight: bold">Phase IV: Testing Phase (July 10-Launch)</p>
  <p align="justify">This is when each of the components will be tested many  times and in all possible ways until we are sure that the satellite is capable of handling conditions found in space. The satellite will undergo various tests in this phase - ThermoVac tests, Radiation tests, Vibration tests etc to ensure the robustness of various components.</p>
  <?php	include('footer.php');?>
