<!DOCTYPE html>
<html>
<head>
    <title>Mechanical Subsystem &mdash; Student Satellite Project &mdash; IIT Bombay</title>
</head>
<body>
    <?php include('header.php'); ?>
    
    <div class="pg-top" style="background: url('images/mechBG.jpeg'); background-size: cover; background-attachment: fixed;">
        <div class="container subs">
            <div class="center wow fadeInDown">

                <div class="text-center pb-1 border-primary mb-4">
                    <h2 class="text-primary">MECHANICAL</h2>
                </div>

                <div class="row">
                    <div class=" col-md-1"></div>
                    <div class="col-md-10">
                        <p>The mechanical subsystem consists of three sections: <b>Structures</b>, <b>Thermals</b> and <b>Integration</b>. The broad function of this subsystem is to design the body of the satellite and mount all components on it, shielding them well from shock, excessive temperatures, radiation and stray magnetic fields, control the internal thermal environment at all times and design mechanisms crucial to the working of components.</p>

                        <p>This subsystem is responsible for choosing the optimal shape, material and framework for the satellite body by simulating loading conditions during launch and in orbit, communicate weight and dimension constraints to other subsystems, provide means of mounting, fastening and cushioning all components securely, dissipate excess heat generated by the components, maintain steady temperature conditions within the satellite and protect the components from the harsh space environment, provide routing for the various power and data cables used, interface the satellite to the launch vehicle and fabricate the final flight model of the satellite and test it for resistance to shocks and thermal vacuum conditions.</p>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-12" style="padding-bottom: 20px;"></div>
                </div>
            </div>
        </div>
    </div>

    <?php include('footer.php'); ?>

</body>
</html>